### ISSUE TITLE
Duplicated log message in Django

### ISSUE THREAD

**Issue by charlee** [villainy/grpc-accesslog#424]
When used in django, the access log shown in console is duplicated with general logging setting.

## How to reproduce

Start the GRPC server with the following code, specifying the logger name as `grpc`:

```python
        interceptors = [AccessLogInterceptor(name='grpc')]
        server = grpc.server(futures.ThreadPoolExecutor(), interceptors=interceptors)
```

Then in django `settings.py`, setup logging:
```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'grpc': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
```

This setup results in every log entry being duplicated in the console, e.g.

```
%5B::1%5D [31/Mar/2024:16:45:43 +0000] /PageService/GetPage OK 74 grpc-python/1.62.1 grpc-c/39.0.0 (linux; chttp2)
%5B::1%5D [31/Mar/2024:16:45:43 +0000] /PageService/GetPage OK 74 grpc-python/1.62.1 grpc-c/39.0.0 (linux; chttp2)
```

## Reason

The `AccessLogInterceptor` is attaching a logging handler to the logger ([src](https://github.com/villainy/grpc-accesslog/blob/master/src/grpc_accesslog/_server.py#L85)):
```python
        self._logger = logging.getLogger(name)
        self._logger.propagate = propagate
        self._logger.addHandler(logging.StreamHandler())
```
With the above django setting, the `grpc` logger has two loggers which cause the duplicated log entries.

## How to fix it

A workaround is not to specify any handler in django, e.g. 
```python
        'grpc': {
            'handlers': [],
            'level': 'DEBUG',
            'propagate': False,
        },
```

However, the handler assigned in the `AccessLogInterceptor` (as well as the `propagate`) actually limited the ability of the logger. The consumer should have the responsibility to setup the logger's handler and propagate to tailor it to their needs.

I would recommend removing the `self.logger.addHandler(logging.SteamHandler())` line, and state in the document that the consumer should prepare the handler for the logger. 

Another more aggresive but more compatible way is to provide an alternative constructor that accepts a predefined logger, instead of calling `getLogger` inside the constructor. For example:

```python
class AccessLogInteceptor(grpc.ServerInterceptor):
    def __init__(self, level, name, handlers, separator, propagate, logger=None):
        ...
        if logger is not None:
            self._logger = logger
        else:
            self._logger = logging.getLogger(name)
            ...
```

**Comment by charlee** [comment]
Please let me know your thoughts! I could also submit a PR if you can decide which approach is better.

**Comment by villainy** [comment]
Allowing a custom logger passed into the constructor makes sense. This should be fixed by #426. I have one more small fix to merge and I should be able to 0.2.1 release this evening. Thanks!

**Comment by villainy** [comment]
0.2.1 released including the new logger param. You should be all set.

**Comment by charlee** [comment]
@villainy Thank you so much! Tested on 0.3.0 and verified that this is fixed. Will close the issue.
